### ISSUE TITLE
Chrome

### ISSUE THREAD

**Issue by fuzeman** [NeApp/neon-extension#14]
Release on the Chrome Web Store.

### Tasks

- [x] Update the interface package
- [x] Update the builder package
- [x] Ensure content script registration is working
- [x] Ensure permission requests are working
- [x] Release on Chrome Web Store

-------------

### Requires
 - [x] #2

**Comment by fuzeman** [comment]
Available at https://chrome.google.com/webstore/detail/neon/bmhcjgenhkdgfahhhnhmefdofjhakphj
