### ISSUE TITLE
Opera

### ISSUE THREAD

**Issue by fuzeman** [NeApp/neon-extension#15]
Release on https://addons.opera.com

### Tasks

- [x] Create browser package
- [x] Ensure content script registration is working
- [x] Ensure permission requests are working
- [ ] Release on https://addons.opera.com

**Comment by fuzeman** [comment]
v1.8.0 is currently awaiting review.
